-- MySQL Script generated by MySQL Workbench
-- Tue Dec 14 03:50:10 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP DATABASE IF EXISTS ATMmanagmentDB;
CREATE DATABASE IF NOT EXISTS ATMmanagementDB;
USE ATMmanagementDB;
-- -----------------------------------------------------
-- Table `Address`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Address` ;

CREATE TABLE IF NOT EXISTS `Address` (
  `address_id` TINYINT(1) NOT NULL,
  `address` VARCHAR(45) NOT NULL,
  `city` VARCHAR(45) NOT NULL,
  `state` CHAR(2) NOT NULL,
  `zip_code` VARCHAR(16) NOT NULL,
  PRIMARY KEY (`address_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RegisteredUser`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `RegisteredUser` ;

CREATE TABLE IF NOT EXISTS `RegisteredUser` (
  `user_id` TINYINT(1) NOT NULL,
  `full_name` VARCHAR(45) NOT NULL,
  `user_email` VARCHAR(45) NOT NULL,
  `dob` VARCHAR(32) NOT NULL,
  `user_address` TINYINT(1) NOT NULL,
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `email_UNIQUE` (`user_email` ASC),
  INDEX `user_address_idx` (`user_address` ASC),
  CONSTRAINT `user_address`
    FOREIGN KEY (`user_address`)
    REFERENCES `Address` (`address_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE);


-- -----------------------------------------------------
-- Table `Language`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Language` ;

CREATE TABLE IF NOT EXISTS `Language` (
  `language_id` TINYINT(1) NOT NULL,
  `description` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`language_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Account`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Account` ;

CREATE TABLE IF NOT EXISTS `Account` (
  `account_id` TINYINT(1) NOT NULL,
  `reg_user` TINYINT(1) NOT NULL,
  `languages` TINYINT(1) NOT NULL,
  `created` DATETIME NOT NULL,
  `password` VARCHAR(100) NOT NULL,
  INDEX `user_id_idx` (`reg_user` ASC),
  PRIMARY KEY (`account_id`),
  INDEX `ACCOUNT_LANGUAGE_FK_PK_idx` (`languages` ASC),
  CONSTRAINT `ACCOUNT_USER_FK`
    FOREIGN KEY (`reg_user`)
    REFERENCES `RegisteredUser` (`user_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `ACCOUNT_LANGUAGE_FK`
    FOREIGN KEY (`languages`)
    REFERENCES `Language` (`language_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Checking`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Checking` ;

CREATE TABLE IF NOT EXISTS `Checking` (
  `checking_acc_id` TINYINT(1) NOT NULL,
  `account_id` TINYINT(1) NOT NULL,
  `checking_balance` INT NOT NULL,
  PRIMARY KEY (`checking_acc_id`, `account_id`),
  INDEX `CHECKING_ACCOUNT_FK+PK_idx` (`account_id` ASC),
  CONSTRAINT `CHECKING_ACCOUNT_FK+PK`
    FOREIGN KEY (`account_id`)
    REFERENCES `Account` (`account_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Savings`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Savings` ;

CREATE TABLE IF NOT EXISTS `Savings` (
  `savings_acc_id` TINYINT(1) NOT NULL,
  `account_id` TINYINT(1) NOT NULL,
  `savings_balance` INT NOT NULL,
  PRIMARY KEY (`savings_acc_id`, `account_id`),
  INDEX `SAVINGS_ACCOUNT_FK+PK_idx` (`account_id` ASC),
  CONSTRAINT `SAVINGS_ACCOUNT_FK+PK`
    FOREIGN KEY (`account_id`)
    REFERENCES `Account` (`account_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Region`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Region` ;

CREATE TABLE IF NOT EXISTS `Region` (
  `region_id` TINYINT(1) NOT NULL,
  `description` VARCHAR(100) NOT NULL,
  `cities` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`region_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Bank`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Bank` ;

CREATE TABLE IF NOT EXISTS `Bank` (
  `bank_id` TINYINT(1) NOT NULL,
  `bank_name` VARCHAR(45) NOT NULL,
  `bank_address` TINYINT(1) NOT NULL,
  PRIMARY KEY (`bank_id`),
  INDEX `bank_address_idx` (`bank_address` ASC),
  CONSTRAINT `bank_address`
    FOREIGN KEY (`bank_address`)
    REFERENCES `Address` (`address_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Keypad`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Keypad` ;

CREATE TABLE IF NOT EXISTS `Keypad` (
  `keypad_id` TINYINT(1) NOT NULL,
  `status` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`keypad_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HandprintScanner`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `HandprintScanner` ;

CREATE TABLE IF NOT EXISTS `HandprintScanner` (
  `scanner_id` TINYINT(1) NOT NULL,
  `status` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`scanner_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DebitCard`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DebitCard` ;

CREATE TABLE IF NOT EXISTS `DebitCard` (
  `debit_card_id` TINYINT(1) NOT NULL,
  `user` TINYINT(1) NOT NULL,
  `card_num` VARCHAR(16) NOT NULL,
  `card_pin` VARCHAR(4) NOT NULL,
  `card_exp` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `cvv` VARCHAR(3) NOT NULL,
  PRIMARY KEY (`debit_card_id`),
  UNIQUE INDEX `card_num_UNIQUE` (`card_num` ASC),
  INDEX `user_id_idx` (`user` ASC),
  CONSTRAINT `user_id`
    FOREIGN KEY (`user`)
    REFERENCES `RegisteredUser` (`user_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Network`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Network` ;

CREATE TABLE IF NOT EXISTS `Network` (
  `network_id` TINYINT(1) NOT NULL,
  `status` VARCHAR(45) NOT NULL,
  `connection_name` VARCHAR(45) NULL,
  PRIMARY KEY (`network_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PoliceStation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PoliceStation` ;

CREATE TABLE IF NOT EXISTS `PoliceStation` (
  `pol_station_id` TINYINT(1) NOT NULL,
  `pol_address` TINYINT(1) NOT NULL,
  `pol_email` VARCHAR(45) NULL,
  PRIMARY KEY (`pol_station_id`),
  UNIQUE INDEX `email_UNIQUE` (`pol_email` ASC),
  INDEX `pol_address_idx` (`pol_address` ASC),
  CONSTRAINT `pol_address`
    FOREIGN KEY (`pol_address`)
    REFERENCES `Address` (`address_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ATM`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ATM` ;

CREATE TABLE IF NOT EXISTS `ATM` (
  `atm_id` TINYINT(1) NOT NULL,
  `bank` TINYINT(1) NOT NULL,
  `region` TINYINT(1) NOT NULL,
  `keypad` TINYINT(1) NOT NULL,
  `handprint_scanner` TINYINT(1) NOT NULL,
  `debit` TINYINT(1) NOT NULL,
  `network` TINYINT(1) NOT NULL,
  `police_station` TINYINT(1) NOT NULL,
  `status` VARCHAR(45) NOT NULL,
  `polAlerts` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`atm_id`),
  INDEX `region_idx` (`region` ASC),
  INDEX `bank_idx` (`bank` ASC),
  INDEX `keypad_idx` (`keypad` ASC),
  INDEX `hscan_idx` (`handprint_scanner` ASC),
  INDEX `debit_idx` (`debit` ASC),
  INDEX `network_idx` (`network` ASC),
  INDEX `police_idx` (`police_station` ASC),
  CONSTRAINT `region_idx`
    FOREIGN KEY (`region`)
    REFERENCES `Region` (`region_id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `ATM_BANK_FK_PK`
    FOREIGN KEY (`bank`)
    REFERENCES `Bank` (`bank_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `ATM_KEYPAD_FK`
    FOREIGN KEY (`keypad`)
    REFERENCES `Keypad` (`keypad_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `ATM_HSCAN_FK`
    FOREIGN KEY (`handprint_scanner`)
    REFERENCES `HandprintScanner` (`scanner_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `ATM_DEBIT_FK`
    FOREIGN KEY (`debit`)
    REFERENCES `DebitCard` (`debit_card_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `ATM_NETWORK_FK`
    FOREIGN KEY (`network`)
    REFERENCES `Network` (`network_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `ATM_POLICE_FK`
    FOREIGN KEY (`police_station`)
    REFERENCES `PoliceStation` (`pol_station_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Employee`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Employee` ;

CREATE TABLE IF NOT EXISTS `Employee` (
  `bank` TINYINT(1) NOT NULL,
  `employee_id` TINYINT(1) NOT NULL,
  `is_supervisor` TINYINT(1) NULL,
  `employee_name` VARCHAR(45) NOT NULL,
  `employee_email` VARCHAR(45) NOT NULL,
  `employee_salary` VARCHAR(45) NOT NULL,
  `employee_dob` VARCHAR(45) NOT NULL,
  INDEX `bank_id_idx` (`bank` ASC),
  PRIMARY KEY (`employee_id`),
  UNIQUE INDEX `employee_email_UNIQUE` (`employee_email` ASC),
  CONSTRAINT `bank_id`
    FOREIGN KEY (`bank`)
    REFERENCES `Bank` (`bank_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Admin`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Admin` ;

CREATE TABLE IF NOT EXISTS `Admin` (
  `admin_id` TINYINT(1) NOT NULL,
  `employee` TINYINT(1) NOT NULL,
  PRIMARY KEY (`admin_id`, `employee`),
  INDEX `ADMIN_EMPLOYEE_FK+PK_idx` (`employee` ASC),
  CONSTRAINT `ADMIN_EMPLOYEE_FK+PK`
    FOREIGN KEY (`employee`)
    REFERENCES `Employee` (`employee_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ATMTechnician`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ATMTechnician` ;

CREATE TABLE IF NOT EXISTS `ATMTechnician` (
  `tech_id` TINYINT(1) NOT NULL,
  `employee` TINYINT(1) NOT NULL,
  PRIMARY KEY (`tech_id`, `employee`),
  INDEX `TECH_EMPLOYEE_idx` (`employee` ASC),
  CONSTRAINT `ATMTECH_EMPLOYEE_FK_PK`
    FOREIGN KEY (`employee`)
    REFERENCES `Employee` (`employee_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Cash`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Cash` ;

CREATE TABLE IF NOT EXISTS `Cash` (
  `cash_id` TINYINT(1) NOT NULL,
  `cash_amount` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`cash_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Checks`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Checks` ;

CREATE TABLE IF NOT EXISTS `Checks` (
  `check_id` TINYINT(1) NOT NULL,
  `check_amount` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`check_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Supply`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Supply` ;

CREATE TABLE IF NOT EXISTS `Supply` (
  `sup_id` TINYINT(1) NOT NULL,
  `atm` TINYINT(1) NOT NULL,
  `admin` TINYINT(1) NOT NULL,
  `tech` TINYINT(1) NOT NULL,
  `cash` TINYINT(1) NOT NULL,
  `checks` TINYINT(1) NOT NULL,
  `status` VARCHAR(45) NOT NULL,
  `alarms_sent` INT NOT NULL,
  PRIMARY KEY (`sup_id`, `atm`),
  INDEX `SUPPLY_ADMIN_FK_idx` (`admin` ASC),
  INDEX `SUPPLY_TECH_FK_idx` (`tech` ASC),
  INDEX `SUPPLY_ATM_FK_idx` (`atm` ASC),
  INDEX `SUPPLY_CASH_FK_idx` (`cash` ASC),
  INDEX `SUPPLY_CHECKS_FK_idx` (`checks` ASC),
  CONSTRAINT `SUPPLY_ADMIN_FK`
    FOREIGN KEY (`admin`)
    REFERENCES `Admin` (`admin_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `SUPPLY_TECH_FK`
    FOREIGN KEY (`tech`)
    REFERENCES `ATMTechnician` (`tech_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `SUPPLY_ATM_FK`
    FOREIGN KEY (`atm`)
    REFERENCES `ATM` (`atm_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `SUPPLY_CASH_FK`
    FOREIGN KEY (`cash`)
    REFERENCES `Cash` (`cash_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `SUPPLY_CHECKS_FK`
    FOREIGN KEY (`checks`)
    REFERENCES `Checks` (`check_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Phone`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Phone` ;

CREATE TABLE IF NOT EXISTS `Phone` (
  `phone_id` TINYINT(1) NOT NULL,
  `user_phone` TINYINT(1) NOT NULL,
  PRIMARY KEY (`phone_id`),
  INDEX `PHONE_USER_FK_idx` (`user_phone` ASC),
  CONSTRAINT `PHONE_USER_FK`
    FOREIGN KEY (`user_phone`)
    REFERENCES `RegisteredUser` (`user_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Session`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Session` ;

CREATE TABLE IF NOT EXISTS `Session` (
  `session_id` TINYINT(1) NOT NULL,
  `session_create` DATETIME NOT NULL,
  `reg_user` TINYINT(1) NOT NULL,
  `atm` TINYINT(1) NOT NULL,
  `phone` TINYINT(1) NULL,
  PRIMARY KEY (`session_id`),
  INDEX `user_idx` (`reg_user` ASC),
  INDEX `SESSION_ATM_FK_idx` (`atm` ASC),
  INDEX `SESSION_PHONE_FK_idx` (`phone` ASC),
  CONSTRAINT `user`
    FOREIGN KEY (`reg_user`)
    REFERENCES `RegisteredUser` (`user_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `SESSION_ATM_FK`
    FOREIGN KEY (`atm`)
    REFERENCES `ATM` (`atm_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `SESSION_PHONE_FK`
    FOREIGN KEY (`phone`)
    REFERENCES `Phone` (`phone_id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Transaction`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Transaction` ;

CREATE TABLE IF NOT EXISTS `Transaction` (
  `transaction_id` TINYINT(1) NOT NULL,
  `sessions` TINYINT(1) NOT NULL,
  PRIMARY KEY (`transaction_id`),
  INDEX `TRANSACTION_SESS_FK_PK_idx` (`sessions` ASC),
  CONSTRAINT `TRANSACTION_SESS_FK_PK`
    FOREIGN KEY (`sessions`)
    REFERENCES `Session` (`session_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Inquire`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Inquire` ;

CREATE TABLE IF NOT EXISTS `Inquire` (
  `inquire_id` TINYINT(1) NOT NULL,
  `transaction_id` TINYINT(1) NOT NULL,
  `balance` INT NOT NULL,
  PRIMARY KEY (`inquire_id`, `transaction_id`),
  INDEX `INQUIRE_TRANS_FK_PK_idx` (`transaction_id` ASC),
  CONSTRAINT `INQUIRE_TRANS_FK_PK`
    FOREIGN KEY (`transaction_id`)
    REFERENCES `Transaction` (`transaction_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Withdraw`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Withdraw` ;

CREATE TABLE IF NOT EXISTS `Withdraw` (
  `withdraw_id` TINYINT(1) NOT NULL,
  `transaction_id` TINYINT(1) NOT NULL,
  `withdraw_limit` INT NOT NULL,
  `amount` INT NOT NULL,
  PRIMARY KEY (`withdraw_id`, `transaction_id`),
  INDEX `WITHDRAW_TRANS_FK_PK_idx` (`transaction_id` ASC),
  CONSTRAINT `WITHDRAW_TRANS_FK_PK`
    FOREIGN KEY (`transaction_id`)
    REFERENCES `Transaction` (`transaction_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Transfer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Transfer` ;

CREATE TABLE IF NOT EXISTS `Transfer` (
  `transfer_id` TINYINT(1) NOT NULL,
  `transaction_id` TINYINT(1) NOT NULL,
  `amount` INT NOT NULL,
  PRIMARY KEY (`transfer_id`, `transaction_id`),
  INDEX `TRANSFER_TRANS_FK_PK_idx` (`transaction_id` ASC),
  CONSTRAINT `TRANSFER_TRANS_FK_PK`
    FOREIGN KEY (`transaction_id`)
    REFERENCES `Transaction` (`transaction_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Deposit`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Deposit` ;

CREATE TABLE IF NOT EXISTS `Deposit` (
  `deposit_id` TINYINT(1) NOT NULL,
  `transaction_id` TINYINT(1) NOT NULL,
  `amount` INT NOT NULL,
  PRIMARY KEY (`deposit_id`, `transaction_id`),
  INDEX `DEPOSIT_TRANS_FK_PK_idx` (`transaction_id` ASC),
  CONSTRAINT `DEPOSIT_TRANS_FK_PK`
    FOREIGN KEY (`transaction_id`)
    REFERENCES `Transaction` (`transaction_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Teller`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Teller` ;

CREATE TABLE IF NOT EXISTS `Teller` (
  `teller_id` TINYINT(1) NOT NULL,
  `employee` TINYINT(1) NOT NULL,
  PRIMARY KEY (`teller_id`, `employee`),
  INDEX `TELLER_EMPLOYEE_FK+PK_idx` (`employee` ASC),
  CONSTRAINT `TELLER_EMPLOYEE_FK+PK`
    FOREIGN KEY (`employee`)
    REFERENCES `Employee` (`employee_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Bills`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Bills` ;

CREATE TABLE IF NOT EXISTS `Bills` (
  `bills_id` TINYINT(1) NOT NULL,
  `cash` TINYINT(1) NOT NULL,
  `bills_amount` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`bills_id`, `cash`),
  INDEX `BILLS_MONEY_FK_PK_idx` (`cash` ASC),
  CONSTRAINT `BILLS_MONEY_FK_PK`
    FOREIGN KEY (`cash`)
    REFERENCES `Cash` (`cash_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Coins`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Coins` ;

CREATE TABLE IF NOT EXISTS `Coins` (
  `coins_id` TINYINT(1) NOT NULL,
  `cash` TINYINT(1) NOT NULL,
  `coins_amount` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`coins_id`, `cash`),
  INDEX `COINS_MONEY_FK_PK_idx` (`cash` ASC),
  CONSTRAINT `COINS_MONEY_FK_PK`
    FOREIGN KEY (`cash`)
    REFERENCES `Cash` (`cash_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Supervisor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Supervisor` ;

CREATE TABLE IF NOT EXISTS `Supervisor` (
  `employee` TINYINT(1) NOT NULL,
  `supervisor` TINYINT(1) NOT NULL,
  PRIMARY KEY (`employee`),
  CONSTRAINT `is_supervisor`
    FOREIGN KEY (`employee`)
    REFERENCES `Employee` (`employee_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CashChecks`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CashChecks` ;

CREATE TABLE IF NOT EXISTS `CashChecks` (
  `cash` TINYINT(1) NOT NULL,
  `checks` TINYINT(1) NOT NULL,
  INDEX `CHECK_MONEY_idx` (`checks` ASC),
  INDEX `CASH_MONEY_idx` (`cash` ASC),
  PRIMARY KEY (`cash`, `checks`),
  CONSTRAINT `CASHCHECK_CHECKS_FK_PK`
    FOREIGN KEY (`checks`)
    REFERENCES `Checks` (`check_id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `CASHCHECK_CASH_FK_PK`
    FOREIGN KEY (`cash`)
    REFERENCES `Cash` (`cash_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `System`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `System` ;

CREATE TABLE IF NOT EXISTS `System` (
  `system_id` TINYINT(1) NOT NULL,
  `supply` TINYINT(1) NOT NULL,
  `supply_status` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`system_id`),
  INDEX `SYSTEM_SUPP_FK_idx` (`supply` ASC),
  CONSTRAINT `SYSTEM_SUPP_FK`
    FOREIGN KEY (`supply`)
    REFERENCES `Supply` (`sup_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AtmUpdatesAccount`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `AtmUpdatesAccount` ;

CREATE TABLE IF NOT EXISTS `AtmUpdatesAccount` (
  `account` TINYINT(1) NOT NULL,
  `atm` TINYINT(1) NOT NULL,
  PRIMARY KEY (`account`, `atm`),
  INDEX `fk_Account_has_ATM_ATM1_idx` (`atm` ASC),
  INDEX `fk_Account_has_ATM_Account1_idx` (`account` ASC),
  CONSTRAINT `fk_Account_has_ATM_Account1`
    FOREIGN KEY (`account`)
    REFERENCES `Account` (`account_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Account_has_ATM_ATM1`
    FOREIGN KEY (`atm`)
    REFERENCES `ATM` (`atm_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Receipt`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Receipt` ;

CREATE TABLE IF NOT EXISTS `Receipt` (
  `receipt_id` TINYINT(1) NOT NULL,
  `sessions` TINYINT(1) NOT NULL,
  PRIMARY KEY (`receipt_id`, `sessions`),
  INDEX `RECEIPT_SESSION_FK_PK_idx` (`sessions` ASC),
  CONSTRAINT `RECEIPT_SESSION_FK_PK`
    FOREIGN KEY (`sessions`)
    REFERENCES `Session` (`session_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
